export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_WARNING = "ALERT_WARNING";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_REMOVE = "ALERT_REMOVE";

export const CURRENT_WEATHER_GET = "CURRENT_WEATHER_GET";
export const CURRENT_WEATHER_GET_SUCCESS = "CURRENT_WEATHER_GET_SUCCESS";
export const CURRENT_WEATHER_GET_ERROR = "CURRENT_WEATHER_GET_ERROR";

export const LOCATION_BY_IP = "LOCATION_BY_IP";
export const LOCATION_GEOCODE = "LOCATION_GEOCODE";
export const LOCATION_SET = "LOCATION_SET";

export const MYIP_GET = "MYIP_GET";
export const MYIP_GET_SUCCESS = "MYIP_GET_SUCCESS";
export const MYIP_GET_ERROR = "MYIP_GET_ERROR";

export const WEATHER_GET = "WEATHER_GET";
export const WEATHER_GET_SUCCESS = "WEATHER_GET_SUCCESS";
export const WEATHER_GET_ERROR = "WEATHER_GET_ERROR";